services:
  - type: web
    name: quiniela-loteka-analysis
    env: python
    buildCommand: "python -m pip install --upgrade pip && pip install -r render-requirements.txt"
    startCommand: "streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true"
    plan: starter
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_SERVER_PORT
        value: "$PORT"
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: "false"
    scaling:
      minInstances: 1
      maxInstances: 1